name: screenshot_freehand
description: Screen shot package like native screen shot on windows.
version: 1.0.1+1
repository: https://github.com/mohammedjmosalam/screenshot_freehand

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # state margent
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  #icon
  ionicons: ^0.2.2
  # editing in image 
  image: ^4.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
